# Generated by Django 5.2.8 on 2025-12-11 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Workout type',
                'verbose_name_plural': 'Workout types',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('distance_m', models.IntegerField()),
                ('duration_sec', models.IntegerField()),
                ('avg_power', models.IntegerField(blank=True, null=True)),
                ('avg_hr', models.IntegerField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.workout')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.workouttype'),
        ),
    ]
