# Generated by Django 5.2.8 on 2025-12-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'managed': False, 'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='workouttype',
            options={'managed': False, 'verbose_name': 'Workout type', 'verbose_name_plural': 'Workout types'},
        ),
    ]
