# Generated by Django 5.2.8 on 2025-12-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_run_options_alter_workouttype_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='run',
            table='runs',
        ),
        migrations.AlterModelTable(
            name='workouttype',
            table='wt',
        ),
    ]
