# Generated by Django 5.2.8 on 2025-12-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_run_table_alter_workouttype_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workouttype',
            table='workout_types',
        ),
    ]
