# Generated by Django 5.2.8 on 2025-12-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_workouttype_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='run',
            table='r',
        ),
    ]
