# Generated by Django 5.2.8 on 2025-12-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_run_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='run',
            table='runs',
        ),
    ]
