# Generated by Django 5.2.8 on 2025-12-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_run_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workouttype',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='workout_name',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='workout_type',
        ),
    ]
