# Generated by Django 5.2.8 on 2025-12-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_workouttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'managed': False},
        ),
    ]
