# Generated by Django 5.2.8 on 2025-12-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_workout_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workout',
            table='workouts',
        ),
    ]
